export const HomePageC = {
  id: 'homePage',
  navBtns: [
    {
      id: 'previous',
      icon: '/svgs/home-page/previous.svg',
      alt: 'previous',
    },
    {
      id: 'next',
      icon: '/svgs/home-page/next.svg',
      alt: 'next',
    },
  ],
  userMenu: {
    name: 'alcjoao',
    avatar: '/imgs/home-page/my-icon.jpg',
    icon: '/svgs/home-page/low.svg',
    items: [
      {
        id: 'account',
        label: 'Account',
      },
      {
        id: 'profile',
        label: 'Profile',
      },
      {
        id: 'recents',
        label: 'Recents',
      },
      {
        id: 'support',
        label: 'Support',
      },
      {
        id: 'private-session',
        label: 'Private session',
      },
      {
        id: 'settings',
        label: 'Settings',
      },
      {
        id: 'logout',
        label: 'Log out',
      },
    ],
  },
  searchBox: {
    placeholder: 'What do you want play?',
    icon: '/svgs/sidebar/search.svg',
  },
  greeting: {
    morning: 'Good morning',
    afternoon: 'Good afternoon',
    evening: 'Good evening',
  },
  playlists: [
    {
      id: 'liked-songs',
      text: 'Liked Songs',
      img: '/svgs/sidebar/liked-songs.svg',
      alt: 'Liked Songs',
    },
    {
      id: 'hasos',
      text: 'Hasos',
      img: '/imgs/sidebar/hasos.jpg',
      alt: 'Hasos',
    },
    {
      id: 'carovaporII',
      text: 'Caro Vapor II',
      img: '/imgs/sidebar/CVII.jpeg',
      alt: 'Caro Vapor II',
    },
    {
      id: 'xtranho',
      text: 'XTRANHO',
      img: '/imgs/sidebar/xtranho.jpeg',
      alt: 'Xtranho',
    },
    {
      id: 'cemporcentocbjr',
      text: '100% Charlie Brown Jr',
      img: '/imgs/sidebar/CB.jpg',
      alt: '100% Charlie Brown Jr',
    },
    {
      id: 'zero',
      text: 'Zero',
      img: '/imgs/home-page/zero.jpeg',
      alt: 'Zero',
    },
    {
      id: 'bully',
      text: 'Bully',
      img: '/imgs/home-page/Bully.jpg',
      alt: 'Bully',
    },
    {
      id: '333',
      text: '333',
      img: '/imgs/home-page/333.jpeg',
      alt: '333',
    },
    {
      id: 'colapso-global',
      text: 'COLAPSO GLOBAL',
      img: '/imgs/home-page/colapso-global.jpeg',
      alt: 'Colapso Global',
    },
  ],
  firstSubtitle: {
    subititle: 'Made for',
    title: 'alcjoao',
  },
  firstCarousel: [
    {
      id: 'xtranho',
      alt: 'Img Album Xtranho',
      img: '/imgs/sidebar/xtranho.jpeg',
      textCard: 'XTRANHO',
      descripition: 'Matuê, King of Brasilian Trap',
    },
    {
      id: 'bully',
      alt: 'Img Album Bully',
      img: '/imgs/home-page/Bully.jpg',
      textCard: 'Bully',
      descripition: 'Kanye West',
    },
    {
      id: 'carovaporII', // 🔥 corrigido
      alt: 'Img Album CVII',
      img: '/imgs/sidebar/CVII.jpeg',
      textCard: 'Caro Vapor II',
      descripition: 'Don L',
    },
    {
      id: 'zero',
      alt: 'Img Album Zero',
      img: '/imgs/home-page/zero.jpeg',
      textCard: 'ZERO',
      descripition: 'Yung Buda',
    },
    {
      id: 'cemporcentocbjr', // 🔥 corrigido
      alt: 'Img Album CBJR',
      img: '/imgs/sidebar/CB.jpg',
      textCard: '100% Charlie Brown JR',
      descripition: 'CBJR',
    },
    {
      id: 'hasos',
      alt: 'Img Album hasos',
      img: '/imgs/sidebar/hasos.jpg',
      textCard: 'Hasos',
      descripition: 'Baco Exu do Blues',
    },
    {
      id: 'colapso-global', // 🔥 corrigido
      alt: 'Img Album Colapso Global',
      img: '/imgs/home-page/colapso-global.jpeg',
      textCard: 'COLAPSO GLOBAL',
      descripition: 'Teto, WIU',
    },
    {
      id: '333',
      alt: 'Img Album 333',
      img: '/imgs/home-page/333.jpeg',
      textCard: '333',
      descripition: 'Matuê',
    },
  ],
  secondSubtitle: {
    subititle: 'Inspired by your recent activity',
    title: 'Recomended for today.',
  },
  secondCarousel: [
    {
      id: '333',
      alt: 'Img Album 333',
      img: '/imgs/home-page/333.jpeg',
      textCard: '333',
      descripition: 'Balance, Self-knowledge, Evolution.',
    },
    {
      id: 'xtranho',
      alt: 'Img Album Xtranho',
      img: '/imgs/sidebar/xtranho.jpeg',
      textCard: 'XTRANHO',
      descripition: 'Matuê, King of Brasilian Trap, Fuck the American',
    },
    {
      id: 'bully',
      alt: 'Img Album Bully',
      img: 'imgs/home-page/Bully.jpg',
      textCard: 'Bully',
      descripition: 'Kanye West - YE, The greatest of all time',
    },
    {
      id: 'Caro Vapor',
      alt: 'Img Album CVII',
      img: '/imgs/sidebar/CVII.jpeg',
      textCard: 'Caro Vapor II',
      descripition: 'Don L, Idol of your idol, Last bad guy',
    },
    {
      id: 'zero',
      alt: 'Img Album Zero',
      img: 'imgs/home-page/zero.jpeg',
      textCard: 'ZERO',
      descripition: 'Yung Buda, The king of underground sound',
    },
    {
      id: 'cbjr',
      alt: 'Img Album 100%cbjr',
      img: '/imgs/sidebar/CB.jpg',
      textCard: '100% Charlie Brown JR',
      descripition: 'CBJR, Forever!',
    },
    {
      id: 'hasos',
      alt: 'Img Album hasos',
      img: '/imgs/sidebar/hasos.jpg',
      textCard: 'Hasos',
      descripition: 'Only understand those who pass by',
    },
    {
      id: 'colapso global',
      alt: 'Img Album Colapso Global',
      img: '/imgs/home-page/colapso-global.jpeg',
      textCard: 'COLAPSO GLOBAL',
      descripition: 'Theres nothing to talk about 30PRAUM',
    },
  ],
  thirdSubtitle: {
    subititle: 'Brand new music from artist you love',
    title: 'New Releases for you',
  },
  thirdCarousel: [
    {
      id: 'the life of pablo',
      alt: 'Img Album The Life Of Pablo',
      img: '/imgs/home-page/thelifeofpablo.jpeg',
      textCard: 'The Life Of Pablo',
      descripition: 'Album • Kanye West',
    },
    {
      id: 'utopia',
      alt: 'Img Album Utopia',
      img: '/imgs/home-page/utopia.jpeg',
      textCard: 'Utopia',
      descripition: 'Album • Travis Scott',
    },
    {
      id: 'astroworld',
      alt: 'Img Album Astroworld',
      img: '/imgs/home-page/astroword.jpeg',
      textCard: 'Astroworld',
      descripition: 'Album • Travis Scott',
    },
    {
      id: 'rocket power',
      alt: 'Img Album Rocket Power',
      img: '/imgs/home-page/rpq.jpeg',
      textCard: 'Rocket Power',
      descripition: 'Album • Quavo',
    },
    {
      id: 'abaixo de zero',
      alt: 'Img Album Abaixo de Zero',
      img: '/imgs/home-page/abaixodezero.jpeg',
      textCard: 'Abaixo de zero',
      descripition: 'Album • Black Alien',
    },
    {
      id: 'mr. morale & the big steppers',
      alt: 'Img Album Mr. Morale & the Big Steppers',
      img: '/imgs/home-page/mrmorale.jpeg',
      textCard: 'Mr. Morale & the Big Steppers',
      descripition: 'Album • Kendrick Lamar',
    },
    {
      id: 'downhill domination - second edition',
      alt: 'Img Album Downhill Domination - SECOND EDITION',
      img: '/imgs/home-page/dhd2.jpeg',
      textCard: 'Downhill Domination II',
      descripition: 'Album • NIKITO',
    },
    {
      id: 'ye',
      alt: 'Img Album YE',
      img: '/imgs/home-page/ye.jpeg',
      textCard: 'YE',
      descripition: 'Album • Kanye West',
    },
    {
      id: 'heaven or hell',
      alt: 'Img Album Heaven or Hell',
      img: '/imgs/home-page/heavenohhell.jpg',
      textCard: 'Heaven or Hell',
      descripition: 'Album • Don Toliver',
    },
    {
      id: 'damn',
      alt: 'Img Album Damn',
      img: '/imgs/home-page/damn.jpeg',
      textCard: 'DAMN',
      descripition: 'Album • Kendrick Lamar',
    },
  ],
};
