import { HomeTemplate } from '@/templates/home';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Spotify',
  description: 'Generated by create next app',
};

export default function Home() {
  return <HomeTemplate />;
}
