import { HomePage } from '@/templates/home/home-page';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Spotify',
  description: 'Generated by create next app',
};

export default function Home() {
  return <HomePage />;
}
